### ISSUE TITLE
Smart Nora devices offline.

### ISSUE THREAD

**Issue by nager07** [andrei-tatar/node-red-contrib-smartnora#17]
Good companions. It is happening to me that devices that were working on Saturday with smart NORA, stopped working, when I asked Google home or Google home mini to turn on a light, it replied that the Smart Nora service is not available or that the light is not available. Verify in MyNora and the devices appear, I have the most recent version of Smart Nora and in the Node network the Smart Nora nodes appear in OK and the status is green. In the google Home app the devices appear but when I try to change their status, it appears offline. Thank you very much and I am looking forward to your comments.

**Comment by andrei-tatar** [comment]
I had this happen to me as well. I think it's a bug related to the online dead letter. I've been trying to reproduce and fix but not much luch.

Until then a restart of node-red should fix the issue...

**Comment by andrei-tatar** [comment]
Btw, do you have connection issues?

**Comment by nager07** [comment]
Okay. It already works for me although I had already restarted the server several times and it still did not work for me. I solved it by deviculating the old nora service in the Google Home App associated with the Gmail account. I also had to remove the old nora token that each account had associated with in Node Red and so I no longer get the Smart Nora devices without disconnection. Thank you very much for your help.

**Comment by andrei-tatar** [comment]
Just got this error this morning. NORA was not able to sync since last night (it just retried again and again).

```
Apr 26 09:50:22 raspberrypi Node-RED[3209]: 26 Apr 09:50:22 - [warn] unhandled error (trying again in 78.5 sec): request to https://api.smart-nora.eu/client/sync?group=home& failed, reason: connect ETIMEDOUT 142.250.185.179:443
Apr 26 09:50:22 raspberrypi Node-RED[3209]: FetchError: request to https://api.smart-nora.eu/client/sync?group=home& failed, reason: connect ETIMEDOUT 142.250.185.179:443
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at ClientRequest.<anonymous> (/home/pi/node-red-contrib-smartnora/node_modules/node-fetch/lib/index.js:1461:11)
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at ClientRequest.emit (events.js:198:13)
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at TLSSocket.socketErrorListener (_http_client.js:401:9)
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at TLSSocket.emit (events.js:198:13)
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Apr 26 09:50:22 raspberrypi Node-RED[3209]:     at process._tickCallback (internal/process/next_tick.js:63:19)
```
After restarting the node-red service, it worked fine.
Not sure what the underlying issue is that prevents the call to get to the server.

**Comment by mvujica** [comment]
Getting similar error:
```
26 Apr 16:30:09 - [warn] unhandled error (trying again in 81 sec): request to https://api.smart-nora.eu/client/sync?group=%3Cdefault%3E& failed, reason: socket hang up
FetchError: request to https://api.smart-nora.eu/client/sync?group=%3Cdefault%3E& failed, reason: socket hang up
at ClientRequest.<anonymous> (/home/pi/.node-red/node_modules/node-fetch/lib/index.js:1461:11)
at ClientRequest.emit (events.js:198:13)
at TLSSocket.socketOnEnd (_http_client.js:435:9)
at TLSSocket.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
```
Restarting just the flow does not help, restarting node-red, as you suggested does work and nora service is synchronizing again.
My node.js is v10.24.1 and node-red is latest 1.3.3.

With old nora connection issues could be solved by restarting flows that I had configured in daily schedule flow, restarting node-red is not desirable.

If you need more info please advise.
Thanks for this lovely service and keep up.

**Comment by mvujica** [comment]
Thanks for quick reply!
What do you suggest, update node to v14 or wait for your fix?
Had this problem intermittently since I upgraded to smart-nora for 3 days now.

**Comment by andrei-tatar** [comment]
@mvujica for me this was the 2nd time it happened since January.
If it happens more often for you, I would suggest trying to update to node v14 and see if that improves anything.

**Comment by andrei-tatar** [comment]
@mvujica  Found the issue and released v1.0.5: https://github.com/andrei-tatar/node-red-contrib-smartnora/releases/tag/v1.0.5

The problem is that the retry to connect didn't work. It was just showing the same error message over and over again but not really trying to connect. So if for some reason the connection was lost and regained, it wouldn't really connect back.

**Comment by mvujica** [comment]
Great thx.
