### ISSUE TITLE
Issue with newest Build

### ISSUE THREAD

**Issue by rgerrans** [andrei-tatar/node-red-contrib-smartnora#191]
@andrei-tatar Just installed the newest build and am getting these errors after restart:

`nora: Secure - unhandled error (trying again in 68.95 sec): (0 , undici_1.fetch) is not a function
TypeError: (0 , undici_1.fetch) is not a function
    at FirebaseSync.doHttpCall (/opt/node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:218:55)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processTimers (internal/timers.js:494:9)
    at FirebaseSync.handleJob (/opt/node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:169:21)`

**Comment by rgerrans** [comment]
I rolled back to 1.13.16 and the error went away.

**Comment by osvedman** [comment]
Same.

**Comment by andrei-tatar** [comment]
Should be fixed now in `v1.13.8`

**Comment by rgerrans** [comment]
Thanks, looks like no more errors with the updated build.
