### ISSUE TITLE
Strange Firebase issue

### ISSUE THREAD

**Issue by bernardstef** [andrei-tatar/node-red-contrib-smartnora#206]
Hi !

I updated to node red 3 from version 2, and I'ma facing an issue. When I change the status (on/off) of a device on the Google Home app, nothing is sent from the corresponding node in node red. It was working earlier.

Also, I get the error on my debug window : 

```
nora: <default> - unhandled error (trying again in 35.65 sec): HTTP response (502 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
)
Error: HTTP response (502 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
)
    at FirebaseSync.doHttpCall (/home/stef/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:238:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:...
```

And

```
nora: <default> - unhandled error (trying again in 67.85 sec): HTTP response (500 Something went wrong! (4a105abb74ca39b0b5cf1b90b50eb701))
Error: HTTP response (500 Something went wrong! (4a105abb74ca39b0b5cf1b90b50eb701))
    at FirebaseSync.doHttpCall (/home/stef/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:238:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at FirebaseSync.handleJob (/home/stef/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:176:21)
```
What can be done ? I think the problem is on my side ! Thanks for the help or ideas ..  !

**Comment by andrei-tatar** [comment]
@bernardstef Hi, it might be related to this issue: #205 
Are you running v1.15.0?

Can you try upgrading to v1.15.1?

**Comment by bernardstef** [comment]
Hi ! I was indeed on 1.15.0 , update to 1.15.1 fixed it ! Many thanks !!
