### ISSUE TITLE
Potential Hard Stop error in Noce-Red 3.1

### ISSUE THREAD

**Issue by rgerrans** [andrei-tatar/node-red-contrib-smartnora#277]
After trying to upgrade to 3.1, I'm getting the following error on startup that forces a restart in Node-Red. I see the "," in the actions id so don't know if that is something I can fix on my end or is in the code that has to be changed? (I have confirmed that none of those characters are in my UID that I redacted)

> 10 Sep 09:59:26 - [info] nora: authenticated, uid: [redacted]
> 10 Sep 09:59:26 - [info] nora: Home - disconnected
> 10 Sep 09:59:27 - [red] Uncaught Exception:
> 10 Sep 09:59:27 - [error] Error: child failed: path argument was an invalid path = "user/[redacted]/actions/cb8f7c43:c9f72-9259523.f754cb|Home". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
>     at validatePathString (/opt/node-red/node_modules/@firebase/database/src/core/util/validation.ts:352:11)
>     at validateRootPathString (/opt/node-red/node_modules/@firebase/database/src/core/util/validation.ts:373:3)
>     at child (/opt/node-red/node_modules/@firebase/database/src/api/Reference_impl.ts:550:5)
>     at ref (/opt/node-red/node_modules/@firebase/database/src/api/Reference_impl.ts:490:31)
>     at FirebaseSync.watchForActions (/opt/node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:101:46)
>     at /opt/node-red/node_modules/node-red-contrib-smartnora/build/nodes/nora-notify.js:37:60
>     at /opt/node-red/node_modules/rxjs/src/internal/operators/switchMap.ts:109:21
>     at OperatorSubscriber._this._next (/opt/node-red/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
>     at OperatorSubscriber.Subscriber.next (/opt/node-red/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
>     at /opt/node-red/node_modules/rxjs/src/internal/Subject.ts:68:20

**Comment by andrei-tatar** [comment]
@rgerrans Hey, interesting. It seems the naming convention for the node id's has changed.
Is this part of a subflow?

**Comment by andrei-tatar** [comment]
Does that subflow work in the previous node-red version? I admin I never tried adding the nodes in subflows. I'll look into escaping the ids.

**Comment by rgerrans** [comment]
It works great, I've had no issues with it. I have a common change node
that I use to format the text for  the notify node, hence why I went with
subflow. It's just the two nodes so won't be a huge issue to elevate it to
the main flows if needed.

**Comment by andrei-tatar** [comment]
ah, found the issue, will push a fix soon.
Along with some other small fixes

**Comment by rgerrans** [comment]
Interestingly, if I'm not mistaken it looks like the subflow was using an
old notify node. I upgraded and when I re added the node I saw all the
body/subject mappings that I'm 90% weren't in the notify node I had in the
subflow.... So looks like I can replace the subflow with the new Notify
node and skip the remapping.

**Comment by rgerrans** [comment]
NVM.....not enough coffee yet this morning

**Comment by rgerrans** [comment]
I also removed the node from a subflow, so now all is working. Thanks

**Comment by andrei-tatar** [comment]
Published version `1.20.0` which should fix this issue.
