### ISSUE TITLE
Triggering dimmer causes warnings in Firebase update

### ISSUE THREAD

**Issue by Wireheadbe** [andrei-tatar/node-red-contrib-smartnora#3]
When I trigger dimmers via Speech commands, I receive the following warnings:
```
13 Feb 08:21:31 - [warn] [noraf-light:Eetkamer] while updating state update was merged with a new one: Error: update was merged with a new one
    at mergeJob (/data/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:116:33)
    at SafeSubscriber.source.subscribe.event [as _next] (/data/node_modules/node-red-contrib-smartnora/build/index.js:51:29)
    at SafeSubscriber.__tryOrUnsub (/data/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
    at SafeSubscriber.next (/data/node_modules/rxjs/src/internal/Subscriber.ts:207:14)
    at Subscriber._next (/data/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
    at Subscriber.next (/data/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Subject.next (/data/node_modules/rxjs/src/internal/Subject.ts:70:17)
    at GroupBySubscriber._group (/data/node_modules/rxjs/src/internal/operators/groupBy.ts:202:13)
    at GroupBySubscriber._next (/data/node_modules/rxjs/src/internal/operators/groupBy.ts:161:10)
    at GroupBySubscriber.Subscriber.next (/data/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Subject.next (/data/node_modules/rxjs/src/internal/Subject.ts:70:17)
    at Promise (/data/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:165:28)
    at new Promise (<anonymous>)
    at FirebaseSync.queueJob (/data/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:164:16)
    at FirebaseSync.updateState (/data/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:63:20)
    at FirebaseDevice.updateState (/data/node_modules/node-red-contrib-smartnora/build/firebase/device.js:70:29)
```

**Comment by Wireheadbe** [comment]
![dimmer_config](https://user-images.githubusercontent.com/4497972/107846083-2de53f80-6de1-11eb-99d4-acb9df74fa6e.JPG)
Dimmer config for reference

**Comment by xury77** [comment]
I had something similar:
`while updating state update was merged with a new one: Error: update was merged with a new one    at mergeJob (/root/.node-red/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:116:33)    at SafeSubscriber._next (/root/.node-red/node_modules/node-red-contrib-smartnora/build/index.js:51:29)    at SafeSubscriber.__tryOrUnsub (/root/.node-red/node_modules/rxjs/internal/Subscriber.js:205:16)    at SafeSubscriber.next (/root/.node-red/node_modules/rxjs/internal/Subscriber.js:143:22)    at Subscriber._next (/root/.node-red/node_modules/rxjs/internal/Subscriber.js:89:26)    at Subscriber.next (/root/.node-red/node_modules/rxjs/internal/Subscriber.js:66:18)    at Subject.next (/root/.node-red/node_modules/rxjs/internal/Subject.js:60:25)    at GroupBySubscriber._group (/root/.node-red/node_modules/rxjs/internal/operators/groupBy.js:98:19)    at GroupBySubscriber._next (/root/.node-red/node_modules/rxjs/internal/operators/groupBy.js:60:14)    at GroupBySubscriber.Subscribe...`

**Comment by andrei-tatar** [comment]
This is expected if too many updates happen.  I will change the log level to trace for this kind of things.

**Comment by Wireheadbe** [comment]
I had this with just turning on a dimmer bulb. Nothing else concurrent.

**Comment by andrei-tatar** [comment]
Should be fixed with `node-red-contrib-smartnora@1.0.0-alpha.4`

**Comment by Wireheadbe** [comment]
![not_correctly_configured](https://user-images.githubusercontent.com/4497972/108178568-de668280-7104-11eb-805e-9d0f7948b4d4.PNG)
The update solved the issue. However, I did notice that after the update and subsequent restart of node-red; the nodes state that they are "incorrectly configured". I just had to open them and click "OK" and re-deploy the flow.

**Comment by andrei-tatar** [comment]
Yes, because there are some new default values (for RGB/temperature support) that are missing from the previous config. They run just fine with that warning as well...

**Comment by Wireheadbe** [comment]
Yes indeed 👍🏻 Perfect - closing this one.
